name:                amethyst
version:             0.1.0.0
github:              "mesabloo/amethyst"
license:             BSD3
author:              "Mesabloo"
maintainer:          "example@example.com"
copyright:           "2019 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mesabloo/amethyst#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- lens
- polysemy
- polysemy-plugin
- text
- containers
- mtl
- haskeline
- ansi-terminal

library:
  source-dirs: src

executables:
  amethyst-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    dependencies:
    - amethyst

tests:
  amethyst-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amethyst
